AllCops:
  # @see https://docs.rubocop.org/rubocop/configuration.html#pre-processing
  Exclude:
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-performance-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-rake-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-rspec-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-thread-safety-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-yml
  
    - .yardoc/
  
    - brutal/coverage/
  
    - coverage/
  
    - doc/
  
    - pkg/
  
    - test.rb
    - config/**/*

  NewCops: enable
  TargetRubyVersion: 3.2

require:
  - rubocop-gitlab-security
  - rubocop-md

inherit_from:
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/performance.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/rake.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/rspec.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/thread_safety.yml
  - .rubocop_todo.yml

Naming/MethodName:
  Enabled: false

Naming/FileName:
  Enabled: false

# Check with yard instead.
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - README.md

  Include:
    - app/**/*
    - config/**/*
    - test/**/*

Lint/RequireRelativeSelfPath:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

Style/RedundantConstantBase:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison
