inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-md
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  NewCops: enable

  Exclude:
    - test.rb

  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true
